

# Use official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app


# Copy your code
COPY shamsa_module8_4_mcp.py .


# Run the program
CMD ["python","shamsa_module8_4_mcp.py"]

