
# Use official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy your code
COPY shamsa_module7_1.py .

# Run the program
CMD ["python", "shamsa_module7_1.py"]



#install docker for windows at your desktop

# RUN IN TERMINAL :
# docker buildx build --load -t shamsa_ex1:1.0.0 .

# to save my image:
# docker save shamsa_ex1:1.0.0 -o shamsa_ex1.tar

#to load my image(future)
# docker load -i shamsa_ex1.tar